# Generated by Django 4.1.5 on 2023-02-04 05:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='abnormal.jpg', upload_to='images/post'),
        ),
    ]
