# Generated by Django 4.1.5 on 2023-02-04 05:39

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlepost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='images/post/abnormal.jpg', upload_to='images/post/'),
        ),
    ]
